### ISSUE TITLE
Código de seguranca (CVV) deve ser enviado ao /payment e não ao /card

### ISSUE THREAD

**Issue by ClaudioMeinberg** [wilbert/aceitafacil#2]
O código de segurança não pode ser salvo em hipótese alguma, logo não precisa ser enviado na geração do cartão:

```
Aceitafacil::Card.new
```

Deve ser enviado no momento do pagamento

```
Payment.new
```

**Comment by ClaudioMeinberg** [comment]
Tentei fazer a alteração para mandar um pull request mas como não conheço a fundo Rails fiquei inseguro ;)

**Comment by wilbert** [comment]
Pode deixar Cláudio, vou fazer a alteração e lhe aviso.

**Comment by wilbert** [comment]
A alteração foi efetuada. Agora o pagamento exige o CVV e o cadastro do cartão não.
